### ISSUE TITLE
Limpiar input 

### ISSUE THREAD

**Issue by lgaticaq** [lgaticaq/shortener-server#12]
el problema es que si pongo una url larga me genera una, ya bacan, pero si quiero generar otra url ya no funciona (porque el input url corta ya tiene texto)

**Comment by juanbrujo** [comment]
para eso se puso el btn Nueva URL

![screen shot 2017-07-28 at 14 59 52](https://user-images.githubusercontent.com/362186/28732319-7cc96804-73a5-11e7-9794-c81a3d5bcf75.png)

**Comment by quest** [comment]
No es un comportamiento natural el "Nueva URL" po @juanbrujo, si genero una URL Corta y luego quiero generar otra lo más común es que borre la URL Larga y escriba una nueva, esperando que en URL Corta aparezca la nueva URL.

Yo creo que la validación debe ir por no querer generar dos URL corta para una misma URL Larga, así evitas un request innecesario al server (se podría agregar LocalStorage si un wn vuelve más tarde y quiere generar URL Corta de una URL Larga que ya generado antes).

Ahora, el botón es súper poco intuitivo, quizás un blur + loading + autocopy es mejor.

**Comment by juanbrujo** [comment]
enterrando

**Comment by quest** [comment]
🙄
