### ISSUE TITLE
Agregar instrucciones para contribucciones

### ISSUE THREAD

**Issue by raerpo** [lgaticaq/shortener-server#16]
Seria posible agregar algunas instrucciones sobre como montar el ambiente de desarrollo? Me gustaría contribuir pero no se como comenzar a hacerlo.

Veo que proyecto usar Docker pero cuando intento levantar el contenedor tengo problemas con lo que asumo es Redis.

La idea seria agregar algo simple como **installation**, **build**, etc.

Podría ser el README o en un CONTRIBUTING.

**Comment by lgaticaq** [comment]
Close with 92942ad
