### ISSUE TITLE
actualizar repo owner

### ISSUE THREAD

**Issue by juanbrujo** [lgaticaq/shortener-server#20]
![screen shot 2017-08-20 at 8 32 31 pm](https://user-images.githubusercontent.com/362186/29499405-c5f6229e-85e6-11e7-9cea-5256a835a688.png)

**Comment by lgaticaq** [comment]
@juanbrujo hace rato te dije que crearas la cuenta de hub.docker.com de devschile para transferir la imagen

**Comment by juanbrujo** [comment]
listoco, u: devschile

**Comment by lgaticaq** [comment]
@juanbrujo cambia las variables de entorno `DOCKER_USERNAME` y `DOCKER_PASSWORD` en https://travis-ci.org/devschile/tupoto/settings

**Comment by lgaticaq** [comment]
Como migramos a netlify, esto ya no va
